apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: logging
data:
  fluent.conf: |
    <match my.logs>
      @type elasticsearch
      host localhost
      port 9200
      logstash_format true
    </match>
