---
apiVersion: batch/v1
kind: Job
metadata:
  name: contour-certgen-v1.11.0
  namespace: projectcontour
spec:
  template:
    spec:
      containers:
      - name: contour
        image: docker.io/projectcontour/contour:v1.11.0
        imagePullPolicy: IfNotPresent
