apiVersion: "cluster.kurl.sh/v1beta1"
kind: "Installer"
metadata:
  name: "base"
spec:
  kubernetes:
    version: "latest"
    serviceCIDR: ""
  docker:
    version: "latest"
    bypassStorageDriverWarnings: true
    hardFailOnLoopback: true
    noCEOnEE: false
  fluentd:
    fullEFKStack: true
