# Source: minio-operator/templates/console-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-console
  namespace: minio
  labels:
    helm.sh/chart: minio-operator-4.0.10
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio
    app.kubernetes.io/version: "v4.0.9"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-operator
      app.kubernetes.io/instance: minio-console
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-operator
        app.kubernetes.io/instance: minio-console
    spec:
      serviceAccountName: console-sa
      containers:
        - name: minio-operator
          image: "minio/console:v0.6.8"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 9090
            name: http
          - containerPort: 9443
            name: https
          args:
          - server
          env:
          - name: CONSOLE_OPERATOR_MODE
            value: "on"
          resources:
            {}
---
