# Source: minio-operator/templates/operator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "operator"
  namespace: minio
  labels:
    helm.sh/chart: minio-operator-4.0.10
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio
    app.kubernetes.io/version: "v4.0.9"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 4222
      name: http
    - port: 4233
      name: https
  selector:
    app.kubernetes.io/name: minio-operator
    app.kubernetes.io/instance: minio
---
