# used to test for fluentd collecting stdout

apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  containers:
  - name: example
    image: replicated/kurl-util:latest
    args: [/bin/sh, -c, 'while true; do echo $(date); sleep 1; done']
