resources:
- grafana-service.yaml 
- grafana-deployment.yaml 
- grafana-dashboardDefinitions.yaml 
- grafana-dashboardDatasources.yaml 
- grafana-dashboardSources.yaml 
- grafana-serviceAccount.yaml 
- grafana-serviceMonitor.yaml

patchesStrategicMerge:
- patches/deployment-admin-user.yaml