apiVersion: apps/v1
kind: Deployment
metadata:
  name: contour
  namespace: heptio-contour
spec:
  template:
    spec:
      containers:
      - name: contour
        imagePullPolicy: IfNotPresent
      - name: envoy
        image: docker.io/envoyproxy/envoy-alpine:v1.10.0
        imagePullPolicy: IfNotPresent
      initContainers:
      - name: envoy-initconfig
        imagePullPolicy: IfNotPresent
