apiVersion: troubleshoot.sh/v1beta2
kind: HostPreflight
metadata:
  name: kurl-builtin
spec:
  collectors:
    - cpu: {}
    - memory: {}
    - diskUsage:
        collectorName: ephemeral
        path: /var/lib/kubelet
  analyzers:
    - cpu:
        outcomes:
          - warn:
              when: "count < 4"
              message: At least 4 CPU cores are required
          - pass:
              message: This server has at least 4 CPU cores
    - memory:
        outcomes:
          - fail:
              when: "< 8Gi"
              message: At least 8Gi of memory is required
          - pass:
              message: The system has at least 8Gi of memory
    - diskUsage:
        collectorName: ephemeral
        outcomes:
          - warn:
              when: "used/total > 70%"
              message: /var/lib/kubelet is more than 70% full
          - fail:
              when: "total < 30Gi"
              message: /var/lib/kubelet has less than 30Gi of total space
          - pass:
              message: /var/lib/kubelet has at least 30Gi disk space available
