# WARNING - containerd add-on references this filename
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  type: ClusterIP
  ports:
  - port: 443
    name: registry
    targetPort: 443
    protocol: TCP
  selector:
    app: registry
