apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kotsadm-role
  labels:
    kots.io/kotsadm: "true"
rules:
- apiGroups:
  - ""
  resourceNames:
  - kotsadm-application-metadata
  - kotsadm-gitops
  resources:
  - configmaps
  verbs:
  - get
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - kotsadm-encryption
  - kotsadm-gitops
  resources:
  - secrets
  verbs:
  - get
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kotsadm-rolebinding
  labels:
    kots.io/kotsadm: "true"
subjects:
- kind: ServiceAccount
  name: kotsadm
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kotsadm-role
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotsadm
  template:
    metadata:
      labels:
        app: kotsadm
        kots.io/kotsadm: "true"
    spec:
      securityContext:
        runAsUser: 1001
      serviceAccountName: kotsadm
      containers:
      - image: kotsadm/kotsadm:v1.11.0
        name: kotsadm
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          httpGet:
            path: /healthz
            port: 3000
            scheme: http
        env:
          - name: SHARED_PASSWORD_BCRYPT
            valueFrom:
              secretKeyRef:
                name: kotsadm-password
                key: passwordBcrypt
          - name: SESSION_KEY
            valueFrom:
              secretKeyRef:
                name: kotsadm-session
                key: passwordBcrypt
          - name: POSTGRES_URI
            valueFrom:
              secretKeyRef:
                name: kotsadm-postgres
                key: uri
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: "true"
spec:
  type: ClusterIP
  selector:
    app: kotsadm
  ports:
  - name: http
    port: 3000
    targetPort: "http"
