apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kotsadm
  template:
    metadata:
      labels:
        app: kotsadm
        kots.io/kotsadm: "true"
    spec:
      securityContext:
        runAsUser: 101
        fsGroup: 101
      volumes:
      - name: kotsadm-scripts
        configMap:
          defaultMode: 511 # hex 777
          name: kotsadm-scripts
      containers:
      - image: kotsadm/kotsadm:v1.11.0
        name: kotsadm
        args:
        - "/scripts/start-kotsadm.sh"
        ports:
        - name: http
          containerPort: 3000
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 2
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
          httpGet:
            path: /healthz
            port: 3000
            scheme: HTTP
        volumeMounts:
        - name: kotsadm-scripts
          mountPath: /scripts/start-kotsadm.sh
          subPath: start-kotsadm.sh
---
apiVersion: v1
kind: Service
metadata:
  name: kotsadm
  labels:
    kots.io/kotsadm: "true"
spec:
  type: ClusterIP
  selector:
    app: kotsadm
  ports:
  - name: http
    port: 3000
    targetPort: "http"
