apiVersion: v1
kind: Service
metadata:
  name: kurl
  labels:
    app: kurl
spec:
  type: NodePort
  ports:
    - name: kurl
      nodePort: 30092
      port: 3000
      targetPort: kurl
  selector:
    app: kurl
