---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: weave-net
  namespace: kube-system
spec:
    spec:
      containers:
        - name: weave
          env:
            - name: WEAVE_PASSWD
              valueFrom:
                secretKeyRef:
                  name: weave-passwd
                  key: weave-passwd
