# This rebuilds a single image
name: build-image
on:
  repository_dispatch:
    types: [build-image]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Install grype
      run: curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b /usr/local/bin
    - name: Install jq
      run: sudo apt-get install -y jq
    - name: Build image ${{ github.event.client_payload.image }}
      env:
        IMAGE: ${{ github.event.client_payload.image }}
      run: |
        make -C $IMAGE
