
name: test-addon-pr.yaml

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Genetate Installer
        id: installer
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_PROD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_PROD_SECRET_ACCESS_KEY }}
          S3_BUCKET: "kurl-sh"
        run: |
          bin/test-addon-pr.sh
          MSG="Testgrid Run Executing @ https://testgrid.kurl.sh/run/pr-$(echo $GITHUB_REF | cut -d/ -f3)-${GITHUB_SHA:0:7}"
          echo "::set-output name=installer_available::$INSTALLER_AVAILABLE"
          echo "::set-output name=installer_spec::$INSTALLER_SPEC"
          echo "::set-output name=msg::$MSG"

      - name: Setup Go
        uses: actions/setup-go@v1
        if: ${{ steps.installer.outputs.installer_available == 'true' }}
        with:
          go-version: 1.15.1

      - name: Tgrun Build
        if: ${{ steps.installer.outputs.installer_available == 'true' }}
        working-directory: ./testgrid/tgrun
        run: make build

      - name: Tgrun Queue
        if: ${{ steps.installer.outputs.installer_available == 'true' }}
        env:
          INSTALLER_SPEC: ${{ steps.installer.outputs.installer_spec }}
        working-directory: ./testgrid/tgrun
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | cut -d"/" -f3)
          ./bin/tgrun queue --staging --ref "pr-${PR_NUMBER}-${GITHUB_SHA:0:7}" --spec "${INSTALLER_SPEC}"

      - name: Post TG URL
        uses: unsplash/comment-on-pr@master
        if: ${{ steps.installer.outputs.installer_available == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          msg: ${{ steps.installer.outputs.msg }}
          check_for_duplicate_msg: true 

